name: 'Hello World'
description: 'greet someone and record etc'
inputs: 
  who-to-greet: #id of input
    description: 'who to greet'
    required: true
    default: 'World'
outputs: 
  time: #id of input
    description: 'The time we greeted you'
  runs: 
    using: 'node12'
    main: 'index.js'